name: other_animations
description: Fancy pre-built animations that can easily be integrated into any Flutter application.
version: 0.0.1
homepage: https://github.com/volskaya/other_animations.flutter

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  sliver_transform: ^0.0.3

dev_dependencies:
  flutter_lints:
  build_runner:
  vector_math: ^2.1.0
